### PR TITLE
Added git version task

### PR DESCRIPTION
**Pull request by CptMoore**
Should create a nice version

modtek_gitversiontask

| Platform | Supported | Works |
| ------------- | ------------- | ------------- |
| Windows  | Yes | Yes |
| Linux | Yes | No |
| macOS | Yes | Yes |

Code to get product version, which contains the SHA1 commit and branch name. Best to show as part of a log.
```
        private static string GetInformationalVersion(this Assembly assembly) {
            var attributes = assembly.GetCustomAttributes(typeof(AssemblyInformationalVersionAttribute), false);

            if (attributes.Length == 0)
            {
                return "";
            }

            return ((AssemblyInformationalVersionAttribute)attributes[0]).InformationalVersion;
        }
```

### CODE REVIEW

**Comment by janxious** [comment]
What steps would you like me to take to test this?

**Comment by CptMoore** [comment]
checkout, restore nuget, build, look if the modtek version is set in the dll

**Comment by Mpstark** [comment]
I can see how this is useful, worked in my setup (as probably everyone expected). This does sort of bring up the fact that we're not using any sort of CI -- and I'll admit, I don't really know much about that side of things.

I'd be fine merging this if everyone else is.

**Comment by CptMoore** [comment]
Yea I think its ready for merging, would like to add the product version to the modtek logs though

**Pull request merged**
