### PR TITLE
Add text to loading screen when load failures occur

### PR DESCRIPTION
**Pull request by Mpstark**
This bypasses the restrictions that we were talking about in issue #101 -- it doesn't block loading going through, doesn't try to "correct" anything, and it checks FYLS log first.

loadfailure

### CODE REVIEW

**Comment by Mpstark** [comment]
That's an interesting idea. The only other loading screen object that I know about is `Briefing`, which is the loading screen with the Leopard.

The only issue that I have with showing all errors in the log is that the base game regularly spits out errors that don't affect gameplay -- showing those to users might not be a good idea, since they might assume that an error displayed might be a real issue and might abort load to deal with the fake issue.

**Comment by Mpstark** [comment]
Thoughts @janxious @m22spencer ?

**Comment by janxious** [comment]
I haven't looked at the PR. Regarding the idea of having logs on screen but it being spammy, I had the same issue which is why I wrote user-defined exclusion into FYLS, which would work just as well if you wanted to put important stuff on the screen.

**Comment by Mpstark** [comment]
I'm merging this at this point, I want to get 0.5.1 on track for release soon, since it has a lot of good error catching stuff

**Pull request merged**
