### PR TITLE
Swap to relative paths in MergeCache/TypeCache/dbCache

### PR DESCRIPTION
**Pull request by Mpstark**
This will allow for users to move their directories and not have to rebuild ModTek caches. This might also allow for modpacks to contain pre-merged, pre-cached installs.

### CODE REVIEW

**Comment by Mpstark** [comment]
A precompiled binary is below. This should handle the transition to relative paths gracefully.

[ModTek.zip](https://github.com/BattletechModders/ModTek/files/2734883/ModTek.zip)

**Comment by Mpstark** [comment]
@janxious Since you're on Mac, this is very important to see if it works for your install.

**Comment by Mpstark** [comment]
I've changed the update to change all of the paths upfront instead of when they're accessed. This should fix the problems that @janxious had with his install.

[ModTek.zip](https://github.com/BattletechModders/ModTek/files/2735152/ModTek.zip)

**Comment by CptMoore** [comment]
Nice, ultimate test would be for a Win user to zip the Mods dir of an RT install and give it to Mac and Linux users.

**Comment by janxious** [comment]
Fixed the issue I ran into last night 👍

**Pull request merged**
